useDotenv: true
disabledDeprecations:
  - AWS_API_GATEWAY_NAME_STARTING_WITH_SERVICE
  - LAMBDA_HASHING_VERSION_V2
service: ddns-lambda
provider:
  name: aws
  runtime: python3.8
  memorySize: 512
  timeout: 10
  endpointType: EDGE
  profile: ddns-lambda
  stage: dev
  region: us-east-1
functions:
  ddns_lambda:
    handler: handler.ddns_lambda
    events:
      - http:
          method: get
          path: nic/update
          integration: lambda-proxy
          request:
            parameters:
              headers:
                authorization: true
              querystrings:
                hostname: true
                myip: false
                offline: false
      - http:
          method: post
          path: nic/update
          integration: lambda-proxy
          request:
            parameters:
              headers:
                Authorization: true
              querystrings:
                hostname: true
                myip: false
                offline: false
    environment:
      DDNS_USERNAME: ${env:DDNS_USERNAME}
      DDNS_PASSWORD: ${env:DDNS_PASSWORD}
plugins:
  - serverless-api-gateway-throttling
custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 2
    maxConcurrentRequests: 1

